#!/bin/bash

# build_model.sh - Builds the custom bashbot model, sourcing ALL
# configuration from the central .env file.

# --- Configuration ---
CONFIG_FILE=".env"
if [ -f "$CONFIG_FILE" ]; then
    set -a
    . "$CONFIG_FILE"
    set +a
    echo "Loaded configuration from $CONFIG_FILE"
else
    echo "FATAL: Configuration file '$CONFIG_FILE' not found."
    exit 1
fi

# --- Create the Modelfile dynamically ---
cat > Modelfile <<EOF
# This Modelfile is dynamically generated by build_model.sh
FROM $BASE_MODEL
SYSTEM """$SYSTEM_PROMPT"""
TEMPLATE """<|start|>system<|message|>You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: 2024-06
Current date: {{ currentDate }}
{{- if and .IsThinkSet .Think (ne .ThinkLevel "") }}

Reasoning: {{ .ThinkLevel }}
{{- else if or (not .IsThinkSet) (and .IsThinkSet .Think) }}

Reasoning: medium
{{- end }}

{{- \$hasNonBuiltinTools := false }}
{{- if .Tools -}}
{{- \$hasBrowserSearch := false }}
{{- \$hasBrowserOpen := false }}
{{- \$hasBrowserFind := false }}
{{- \$hasPython := false }}
  {{- range .Tools }}
    {{- if eq .Function.Name "browser.search" -}}{{- \$hasBrowserSearch = true -}}
    {{- else if eq .Function.Name "browser.open" -}}{{- \$hasBrowserOpen = true -}}
    {{- else if eq .Function.Name "browser.find" -}}{{- \$hasBrowserFind = true -}}
    {{- else if eq .Function.Name "python" -}}{{- \$hasPython = true -}}
    {{- else }}{{ \$hasNonBuiltinTools = true -}}
    {{- end }}
  {{- end }}
{{- if or \$hasBrowserSearch \$hasBrowserOpen \$hasBrowserFind \$hasPython }}

# Tools
{{- if or \$hasBrowserSearch \$hasBrowserOpen \$hasBrowserFind }}

## browser
namespace browser {
{{- if \$hasBrowserSearch }}
type search = (_: {
query: string,
topn?: number,
source?: string,
}) => any;
{{- end }}
{{- if \$hasBrowserOpen }}
type open = (_: {
id?: number | string,
cursor?: number,
loc?: number,
num_lines?: number,
view_source?: boolean,
source?: string,
}) => any;
{{- end }}
{{- if \$hasBrowserFind }}
type find = (_: {
pattern: string,
cursor?: number,
}) => any;
{{- end }}
} // namespace browser
{{- end }}
{{- if \$hasPython }}

## python
{{- end }}
{{- end }}
{{- end }}

# Valid channels: analysis, commentary, final. Channel must be included for every message.{{ if \$hasNonBuiltinTools }}
Calls to these tools must go to the commentary channel: 'functions'.
{{- end -}}<|end|>
{{- if or \$hasNonBuiltinTools .System -}}
<|start|>developer<|message|>{{- if \$hasNonBuiltinTools }}# Tools

## functions
namespace functions {
{{- range .Tools }}
{{- if not (or (eq .Function.Name "browser.search") (eq .Function.Name "browser.open") (eq .Function.Name "browser.find") (eq .Function.Name "python")) }}
{{if .Function.Description }}
// {{ .Function.Description }}
{{- end }}
{{- if and .Function.Parameters.Properties (gt (len .Function.Parameters.Properties) 0) }}
type {{ .Function.Name }} = (_: {
{{- range \$name, \$prop := .Function.Parameters.Properties }}
{{- if \$prop.Description }}
  // {{ \$prop.Description }}
{{- end }}
  {{ \$name }}: {{ if gt (len \$prop.Type) 1 }}{{ range \$i, \$t := \$prop.Type }}{{ if \$i }} | {{ end }}{{ \$t }}{{ end }}{{ else }}{{ index \$prop.Type 0 }}{{ end }},
{{- end }}
}) => any;
{{- else }}
type {{ .Function.Name }} = () => any;
{{- end }}
{{- end }}
{{- end }}
} // namespace functions
{{- end }}
{{- if .System}}

# Instructions
{{ .System }}
{{- end -}}
<|end|>
{{- end -}}
{{- \$lastUserIdx := -1 }}
{{- \$prefillingContent := false }}
{{- \$prefillingThinkingOnly := false }}
{{- range \$i, \$msg := .Messages }}
  {{- \$last := eq (len (slice \$.Messages \$i)) 1 -}}
  {{- if eq \$msg.Role "user" }}
    {{- \$lastUserIdx = \$i }}
  {{- end -}}
  {{- if and \$last (eq \$msg.Role "assistant") (gt (len \$msg.Content) 0) }}
    {{- \$prefillingContent = true }}
  {{- else if and \$last (eq \$msg.Role "assistant") (gt (len \$msg.Thinking) 0) }}
    {{- \$prefillingThinkingOnly = true }}
  {{- end }}
{{- end }}
{{- range \$i, \$msg := .Messages }}
  {{- \$last := eq (len (slice \$.Messages \$i)) 1 -}}
  {{- if (ne \$msg.Role "system") -}}
    {{- if eq \$msg.Role "tool" -}}
      {{- if or (eq \$msg.ToolName "python") (eq \$msg.ToolName "browser.search") (eq \$msg.ToolName "browser.open") (eq \$msg.ToolName "browser.find") -}}
        <|start|>{{ \$msg.ToolName }} to=assistant<|message|>{{ \$msg.Content }}<|end|>
      {{- else -}}
        <|start|>functions.{{ \$msg.ToolName }} to=assistant<|message|>{{ \$msg.Content }}<|end|>
      {{- end -}}
    {{- else if eq \$msg.Role "assistant" -}}
      {{- if and \$msg.Thinking (gt \$i \$lastUserIdx) -}}
      <|start|>assistant<|channel|>analysis<|message|>{{ \$msg.Thinking }}{{- if not \$prefillingThinkingOnly -}}<|end|>{{- end -}}
      {{- end -}}
      {{- if gt (len \$msg.Content) 0 -}}
        <|start|>assistant<|channel|>final<|message|>{{ \$msg.Content }}{{- if not \$prefillingContent -}}<|end|>{{- end -}}
      {{- end -}}
      {{- if gt (len \$msg.ToolCalls) 0 -}}
        {{- range \$j, \$toolCall := \$msg.ToolCalls -}}
          {{- \$isBuiltin := or (eq \$toolCall.Function.Name "python") (eq \$toolCall.Function.Name "browser.search") (eq \$toolCall.Function.Name "browser.open") (eq \$toolCall.Function.Name "browser.find") -}}
          <|start|>assistant<|channel|>{{ if \$isBuiltin }}analysis{{ else }}commentary{{ end }} to={{ if not \$isBuiltin}}functions.{{end}}{{ \$toolCall.Function.Name }} <|constrain|>json<|message|>{{ \$toolCall.Function.Arguments }}<|call|>
        {{- end -}}
      {{- end -}}
    {{- else if eq \$msg.Role "user" -}}
      <|start|>{{ \$msg.Role }}<|message|>{{ \$msg.Content }}<|end|>
    {{- end }}
  {{- else }}
  {{- end }}
{{- end }}
{{- if not (or \$prefillingContent \$prefillingThinkingOnly) -}}
<|start|>assistant
{{- end }}"""
PARAMETER temperature 1
PARAMETER num_ctx $MODEL_CONTEXT_WINDOW
EOF

# --- Build the Model ---
echo "--- Building/updating '$MODEL_NAME' model from generated Modelfile... ---"
ollama create "$MODEL_NAME" -f ./Modelfile
echo "--- Model build complete. ---"
